#!/bin/bash

if type update-alternatives 2>/dev/null >&1; then
    # Remove previous link if it doesn't use update-alternatives
    if [ -L '/usr/bin/local-scribe' -a -e '/usr/bin/local-scribe' -a "`readlink '/usr/bin/local-scribe'`" != '/etc/alternatives/local-scribe' ]; then
        rm -f '/usr/bin/local-scribe'
    fi
    update-alternatives --install '/usr/bin/local-scribe' 'local-scribe' '/opt/LocalScribe/local-scribe' 100 || ln -sf '/opt/LocalScribe/local-scribe' '/usr/bin/local-scribe'
else
    ln -sf '/opt/LocalScribe/local-scribe' '/usr/bin/local-scribe'
fi

# Check if user namespaces are supported by the kernel and working with a quick test:
if ! { [[ -L /proc/self/ns/user ]] && unshare --user true; }; then
    # Use SUID chrome-sandbox only on systems without user namespaces:
    chmod 4755 '/opt/LocalScribe/chrome-sandbox' || true
else
    chmod 0755 '/opt/LocalScribe/chrome-sandbox' || true
fi

if hash update-mime-database 2>/dev/null; then
    update-mime-database /usr/share/mime || true
fi

if hash update-desktop-database 2>/dev/null; then
    update-desktop-database /usr/share/applications || true
fi
