#!/bin/bash

# Delete the link to the binary
if type update-alternatives >/dev/null 2>&1; then
    update-alternatives --remove 'local-scribe' '/usr/bin/local-scribe'
else
    rm -f '/usr/bin/local-scribe'
fi
